apiVersion: v1
kind: Service
metadata:
  name: eks-deployment
  namespace: eks-deployment
  labels:
    app: eks-deployment
spec:
  selector:
    app: eks-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80